// <auto-generated />
namespace SurveyAdmin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Movingsurveymodelsfromapisite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movingsurveymodelsfromapisite));
        
        string IMigrationMetadata.Id
        {
            get { return "201410241739100_Moving survey models from api site"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
