HomeConfig = {
  name: 'H O M E',
  fontFamilies: [
    'Arial',
    'Arial Black',
    'Comic Sans MS',
    'Courier New',
    'Helvetica Neue',
    'Helvetica',
    'Impact',
    'Lucida Grande',
    'Raleway',
    'Tahoma',
    'Times New Roman',
    'Verdana',
  ],
  googleMaps: {
    apiKey: 'AIzaSyC2dPMYEhEoqnUe8LQZK9SVemORszJ-NgE',
  },
  hmisAPIEndpoints: {
    apiBaseUrl: 'https://www.hmislynk.com',
    oauthBaseUrl: 'https://www.hmislynk.com/hmis-authorization-service/rest',
    authorize: '/authorize/',
    token: '/token/',
    revoke: '/revoke/',
    clientBaseUrl: 'https://www.hmislynk.com/hmis-clientapi/rest',
    clients: '/clients/',
    enrollments: '/clients/{{client_id}}/enrollments',
    enrollmentExits: '/clients/{{client_id}}/enrollments/{{enrollmentId}}/exits',
    searchClient: '/search/client',
    projects: '/projects/',
    userServiceBaseUrl: 'https://www.hmislynk.com/hmis-user-service/rest',
    accounts: '/accounts',
    account: '/accounts/{{accountId}}',
    basicInfo: '/accounts/{{username}}/basicinfo',
    selfBasicInfo: '/accounts/self/basicinfo',
    accountRoles: '/accounts/{{accountId}}/roles',
    accountRole: '/accounts/{{accountId}}/roles/{{roleId}}',
    selfPasswordChanges: '/accounts/self/passwordchanges',
    projectGroups: '/projectgroups',
    userProfiles: '/profiles',
    roles: '/roles',
    housingInventoryBaseUrl: 'https://www.hmislynk.com/inventory-api/rest',
    housingUnits: '/housing-units',
    housingUnit: '/housing-units/{{housing_unit_uuid}}',
    globalHouseholdBaseUrl: 'https://www.hmislynk.com/global-household-api',
    globalHouseholds: '/global-households',
    globalHousehold: '/global-households/{{global_household_uuid}}',
    globalHouseholdMembers: '/global-households/{{global_household_uuid}}/members',
    globalHouseholdMember: '/global-households/{{global_household_uuid}}/members/{{membership_id}}',
    globalHouseholdForClient: '/members',
    v2015: '/v2015',
    v2014: '/v2014',
    surveyServiceBaseUrl: 'https://www.hmislynk.com/survey-api/rest',
    responses: '/clients/{{clientid}}/surveys/{{surveyid}}/responses',
    response: '/clients/{{clientid}}/surveys/{{surveyid}}/responses/{{responseid}}',
    sectionScores: '/clients/{{client_id}}/surveys/{{survey_id}}/scores',
    sectionScore: '/clients/{{client_id}}/surveys/{{survey_id}}/sections/{{section_id}}/scores',
    surveyServiceQuestions: '/questiongroups/{{questiongroupid}}/questions',
    surveyServiceQuestion: '/questiongroups/{{questiongroupid}}/questions/{{questionid}}',
    pickListGroups: '/picklistgroups',
    pickListGroup: '/picklistgroups/{{picklistgroupid}}',
    pickListValues: '/picklistgroups/{{picklistgroupid}}/picklistvalues',
    pickListValue: '/picklistgroups/{{picklistgroupid}}/picklistvalues/{{picklistvalueid}}',
    surveys: '/surveys',
    survey: '/surveys/{{surveyid}}',
    surveySections: '/surveys/{{surveyid}}/surveysections',
    surveySection: '/surveys/{{surveyid}}/surveysections/{{sectionid}}',
    surveyQuestions: '/surveys/{{surveyid}}/surveysections/{{sectionid}}/questions',
    surveyQuestion: '/surveys/{{surveyid}}/surveysections/{{sectionid}}/questions/{{questionid}}',
    houseMatchingBaseUrl: 'https://www.hmislynk.com/house-matching-api',
    matches: '/matches',
    match: '/matches/client/{{clientId}}',
    status: '/matches/client/{{clientId}}/status',
    scores: '/scores',
    eligibleClients: '/eligibleclients',
    eligibleClient: '/eligibleclients/{{clientId}}',
    clientScore: '/scores/client/{{clientId}}',
  },
};
