//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyPIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.AspNetRoles = new HashSet<AspNetRoles>();
            this.Groups = new HashSet<Groups>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string AccountType { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
